local/auto_proctor/auto_proctor_dashboard.php

New updated ertu dashboard

---

local/auto_proctor/quizSetting.php

remove test title

---

local/auto_proctor/auto_proctor_dashboard.php
local/auto_proctor/lib.php

AP Dashboard page and nav bar btn restriction

---

local/auto_proctor/quizSetting.php

Kindly  check the new features settings

Updated new setting features frontend

---

local/auto_proctor/quizSetting.php

Revert "Updated new setting features frontend"

---

local/auto_proctor/auto_proctor_dashboard.php

Restricting Quiz Display in AutoProctor

---

local/auto_proctor/testResult.html

ADDING A DRAFT OF TEST RESULT FRONT END -NOT FINALIZE

Add new test result page drraft

---

local/auto_proctor/db/install.xml
local/auto_proctor/quizSetting.php

Adding strict mode in AP table, enabling strict mode

---

local/auto_proctor/proctor_tools/camera_monitoring/monitor_cam.js

Algo for cam sensitivity capture

---

local/auto_proctor/lib.php
local/auto_proctor/proctor_tools/evidences/microphone_capture_evidence/readme.txt
local/auto_proctor/proctor_tools/microphone_monitoring/monitor_mic.js
local/auto_proctor/proctor_tools/microphone_monitoring/save_mic_activity.php
local/auto_proctor/proctor_tools/microphone_monitoring/save_mic_capture.php

Monitor mic feature in plugin implementation

---

local/drafts/selectCamera.html

Modal preparation, modifed modal ui file - angelica

---

local/auto_proctor/ui/testResult.html

redesign test result

---

local/drafts/selectCamera.html

make it radio box

---

local/auto_proctor/ui/prompts.php
local/drafts/selectCamera.html

Apply prepared modal in plugin

---

local/auto_proctor/db/install.xml
local/auto_proctor/lib.php
local/auto_proctor/proctor_tools/proctor_setup/save_proctor_session_setup.php
local/auto_proctor/ui/prompts.php

Setup modal sequence logic, save monitor setup

---

local/auto_proctor/lib.php
local/auto_proctor/ui/prompts.php

prompts, lib comments

---

local/auto_proctor/ui/auto_proctor_dashboard.php

Quiz bank dashboard final modify

---

local/drafts/Home.html

creating a new auto proctor dashboard

adding auto proctor dashboard page

---

local/auto_proctor/ui/courses.php
local/auto_proctor/ui/dashboard_home.php

new update design

---

local/auto_proctor/lib.php
local/auto_proctor/ui/side_navigation_bar.php

Restrict plugin only BSIT

---

local/auto_proctor/ui/auto_proctor_dashboard.php
local/auto_proctor/ui/courses.php
local/auto_proctor/ui/header.php
local/auto_proctor/ui/quiz_results.php
local/auto_proctor/ui/quiz_settings.php
local/auto_proctor/ui/save_quiz_settings.php
local/auto_proctor/ui/side_navigation_bar.php

AP Dashboard

---

local/auto_proctor/ui/quizResult.php

Adding quiz Result in quiz bank

---

local/drafts/archive.html

Adding archive page

---

local/auto_proctor/ui/prompts.php

Prompts exit buttons, display selected camera radio from drop down

---

local/drafts/ViewReport.html

Adding View Report PAGE

---

local/auto_proctor/ui/archives.php
local/auto_proctor/ui/courses.php
local/auto_proctor/ui/dashboard_home.php
local/auto_proctor/ui/side_navigation_bar.php

This is the first batch of update for front end final design and already finalized and check it

FINAL FRONT END UPDATE 1.0

---

local/auto_proctor/ui/quiz_results.php

remove debugging

---

local/auto_proctor/ui/quiz_results.php
local/auto_proctor/ui/quiz_settings.php

FINALIZE THE QUIZ RESULT - MEME

---

local/auto_proctor/ui/archives.php
local/auto_proctor/ui/courses.php
local/auto_proctor/ui/quiz_settings.php
local/auto_proctor/ui/view_report.php

remove debugging scripts

---

local/auto_proctor/ui/archives.php
local/auto_proctor/ui/courses.php
local/auto_proctor/ui/dashboard_home.php
local/auto_proctor/ui/quiz_results.php

Update paganation spacing

---

local/auto_proctor/ui/functions/export_functions.php
local/auto_proctor/ui/prompts.php
local/auto_proctor/ui/quiz_results.php

export initial, modal cam message

---

local/auto_proctor/db/install.xml
local/auto_proctor/lib.php
local/auto_proctor/ui/functions/export_functions.php

export with cam recording, trust score

---

local/auto_proctor/ui/functions/export_functions.php

export include trust score
